// Dados completos das metas - apenas linhas com meta preenchida
const excelData = [
    // HD Itaim
    { especialidade: "Angiologista", servico: "HD Itaim", meta: "1/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "HD Itaim", meta: "3/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "HD Itaim", meta: "1/12h" },
    { especialidade: "Dermatologista", servico: "HD Itaim", meta: "3/12h" },
    { especialidade: "Endocrinologista", servico: "HD Itaim", meta: "2/12h" },
    { especialidade: "GO PNAR", servico: "HD Itaim", meta: "2/12h" },
    { especialidade: "Neurologia", servico: "HD Itaim", meta: "3/12h" },
    { especialidade: "Ortopedia Clinica", servico: "HD Itaim", meta: "4/12h" },
    { especialidade: "Otorrinolaringologista", servico: "HD Itaim", meta: "2/12h" },
    { especialidade: "Pneumo Adulto", servico: "HD Itaim", meta: "1/12h" },
    { especialidade: "Reumato", servico: "HD Itaim", meta: "2/12h" },
    { especialidade: "Urologista", servico: "HD Itaim", meta: "2/12h" },
    { especialidade: "Anestesista Cir.", servico: "HD Itaim", meta: "9/12h" },
    { especialidade: "Dermatologista", servico: "HD Itaim", meta: "1/12h" },
    { especialidade: "Ortopedista", servico: "HD Itaim", meta: "4/12h" },
    { especialidade: "C. Geral", servico: "HD Itaim", meta: "7/12h" },
    { especialidade: "C. Pediatrico", servico: "HD Itaim", meta: "3/12h" },
    { especialidade: "C. Vascular", servico: "HD Itaim", meta: "10/12h" },
    { especialidade: "Urologista", servico: "HD Itaim", meta: "1/12h" },
    { especialidade: "AIH", servico: "HD Itaim", meta: "124" },
    { especialidade: "BPA", servico: "HD Itaim", meta: "460" },
    { especialidade: "Biopsias", servico: "HD Itaim", meta: "80" },
    { especialidade: "Ecocardiograma", servico: "HD Itaim", meta: "350" },
    { especialidade: "Holter", servico: "HD Itaim", meta: "100" },
    { especialidade: "MAPA", servico: "HD Itaim", meta: "100" },
    { especialidade: "Nasofibroscopia", servico: "HD Itaim", meta: "80" },
    { especialidade: "Teste Ergométrico", servico: "HD Itaim", meta: "100" },
    { especialidade: "Ultrassom", servico: "HD Itaim", meta: "750" },
    { especialidade: "Ultrassom Doppler", servico: "HD Itaim", meta: "250" },

    // HD São Miguel
    { especialidade: "Alergista", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Angiologista", servico: "HD São Miguel", meta: "2/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "HD São Miguel", meta: "6/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Dermatologista", servico: "HD São Miguel", meta: "4/12h" },
    { especialidade: "Dermatologista Hanseniase", servico: "HD São Miguel", meta: "1/4h" },
    { especialidade: "Endocrinologista", servico: "HD São Miguel", meta: "5/12h" },
    { especialidade: "Gastroenterologista", servico: "HD São Miguel", meta: "3/12h" },
    { especialidade: "Gastroenterologista Direta", servico: "HD São Miguel", meta: "1/20h" },
    { especialidade: "GO PNAR", servico: "HD São Miguel", meta: "2/12h" },
    { especialidade: "GO Colpo", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Homeopata", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Infecto", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Mastologista", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Nefrologista", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Neurologia", servico: "HD São Miguel", meta: "3/12h" },
    { especialidade: "Ortopedia Clinica", servico: "HD São Miguel", meta: "5/12h" },
    { especialidade: "Otorrinolaringologista", servico: "HD São Miguel", meta: "2/12h" },
    { especialidade: "Otorrinolaringologista direta", servico: "HD São Miguel", meta: "1/20h sms" },
    { especialidade: "Oftalmologista", servico: "HD São Miguel", meta: "2/12h" },
    { especialidade: "Pneumo TISIO Infantil", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Pneumo Adulto", servico: "HD São Miguel", meta: "2/12h" },
    { especialidade: "Pneumo Adulto Direta", servico: "HD São Miguel", meta: "1/20h Tisio SMS" },
    { especialidade: "Reumato", servico: "HD São Miguel", meta: "2/12h" },
    { especialidade: "Urologista", servico: "HD São Miguel", meta: "3/12h" },
    { especialidade: "Anestesista Cir.", servico: "HD São Miguel", meta: "36/12h" },
    { especialidade: "Dermatologista", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "GO", servico: "HD São Miguel", meta: "3/12h" },
    { especialidade: "Masto /PTGI", servico: "HD São Miguel", meta: "1/12h" },
    { especialidade: "Ortopedista", servico: "HD São Miguel", meta: "4/12h" },
    { especialidade: "Otorrino", servico: "HD São Miguel", meta: "8/12h" },
    { especialidade: "C. Geral", servico: "HD São Miguel", meta: "22/12h" },
    { especialidade: "C.Procto", servico: "HD São Miguel", meta: "6/12h" },
    { especialidade: "C. Plastico", servico: "HD São Miguel", meta: "7/12h" },
    { especialidade: "Urologista", servico: "HD São Miguel", meta: "7/12h" },
    { especialidade: "AIH", servico: "HD São Miguel", meta: "350" },
    { especialidade: "BPA", servico: "HD São Miguel", meta: "85" },
    { especialidade: "Ortopedista", servico: "HD São Miguel", meta: "3/12h" },
    { especialidade: "Tec gesso", servico: "HD São Miguel", meta: "1/24h e 1/12h" },
    { especialidade: "Bera com sedação", servico: "HD São Miguel", meta: "5" },
    { especialidade: "Biopsias", servico: "HD São Miguel", meta: "80" },
    { especialidade: "Colono/retossigmoidosc.", servico: "HD São Miguel", meta: "160" },
    { especialidade: "Endoscopia", servico: "HD São Miguel", meta: "280" },
    { especialidade: "Eletroenc. com e sem sed.", servico: "HD São Miguel", meta: "80" },
    { especialidade: "Ecocardiograma", servico: "HD São Miguel", meta: "1452" },
    { especialidade: "Espirometria", servico: "HD São Miguel", meta: "500" },
    { especialidade: "Estudo Urododinâmico", servico: "HD São Miguel", meta: "80" },
    { especialidade: "Holter", servico: "HD São Miguel", meta: "340" },
    { especialidade: "Histeroscopia Diag", servico: "HD São Miguel", meta: "30" },
    { especialidade: "Mamografia", servico: "HD São Miguel", meta: "600" },
    { especialidade: "MAPA", servico: "HD São Miguel", meta: "100" },
    { especialidade: "Holter", servico: "HD São Miguel", meta: "410" },
    { especialidade: "Nasofibroscopia", servico: "HD São Miguel", meta: "350" },
    { especialidade: "Teste Ergométrico", servico: "HD São Miguel", meta: "255" },
    { especialidade: "Ultrassom", servico: "HD São Miguel", meta: "2382" },
    { especialidade: "Ultrassom Doppler", servico: "HD São Miguel", meta: "800" },

    // HD São Mateus
    { especialidade: "Angiologista", servico: "HD São Mateus", meta: "1/6h" },
    { especialidade: "Angiologista Direta", servico: "HD São Mateus", meta: "1/20h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "HD São Mateus", meta: "5/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "HD São Mateus", meta: "1/12h" },
    { especialidade: "Cirurgião Geral", servico: "HD São Mateus", meta: "4/12h" },
    { especialidade: "Dermatologista", servico: "HD São Mateus", meta: "1/6h e 1/12h" },
    { especialidade: "Dermatologista Direta", servico: "HD São Mateus", meta: "2/20h (408)" },
    { especialidade: "Dermatologista Hanseniase", servico: "HD São Mateus", meta: "1/4h" },
    { especialidade: "Endocrinologista", servico: "HD São Mateus", meta: "6/12h" },
    { especialidade: "GO PNAR", servico: "HD São Mateus", meta: "3/12h" },
    { especialidade: "GO", servico: "HD São Mateus", meta: "1/6h e 1/12h" },
    { especialidade: "Hemato", servico: "HD São Mateus", meta: "1/12h" },
    { especialidade: "Infecto", servico: "HD São Mateus", meta: "1/12h" },
    { especialidade: "Mastologista", servico: "HD São Mateus", meta: "1/12h e 1/6h" },
    { especialidade: "Nefrologista", servico: "HD São Mateus", meta: "1/12h" },
    { especialidade: "Neurologia", servico: "HD São Mateus", meta: "1/12h esp." },
    { especialidade: "Ortopedia Clinica", servico: "HD São Mateus", meta: "5/12h e 1/6h" },
    { especialidade: "Otorrinolaringologista", servico: "HD São Mateus", meta: "2/12h e 1/12h (cons. 66/ naso. 40)" },
    { especialidade: "Pneumo Infantil", servico: "HD São Mateus", meta: "1/12h" },
    { especialidade: "Proctologista", servico: "HD São Mateus", meta: "1/6h + 1/12h" },
    { especialidade: "Reumato", servico: "HD São Mateus", meta: "2/12h esp." },
    { especialidade: "Urologista", servico: "HD São Mateus", meta: "3/12h" },
    { especialidade: "Anestesista Cir.", servico: "HD São Mateus", meta: "14/12h dia e 7/12h noite" },
    { especialidade: "Dermatologista", servico: "HD São Mateus", meta: "1/12h" },
    { especialidade: "Dermatologista", servico: "HD São Mateus", meta: "2/12h dia 2/12h noite" },
    { especialidade: "GO", servico: "HD São Mateus", meta: "1/6h e 1/12h" },
    { especialidade: "Masto /PTGI", servico: "HD São Mateus", meta: "1/6h" },
    { especialidade: "Ortopedista", servico: "HD São Mateus", meta: "1/6h" },
    { especialidade: "C. Geral", servico: "HD São Mateus", meta: "5/12h dia 5/12h noite" },
    { especialidade: "C. Pediatrico", servico: "HD São Mateus", meta: "1/12h" },
    { especialidade: "C.Procto", servico: "HD São Mateus", meta: "1/6h dia + 1/12h noite" },
    { especialidade: "C. Vascular", servico: "HD São Mateus", meta: "1/6h" },
    { especialidade: "Urologista", servico: "HD São Mateus", meta: "1/12h e 1/12h noite" },
    { especialidade: "AIH", servico: "HD São Mateus", meta: "388" },
    { especialidade: "BPA", servico: "HD São Mateus", meta: "300" },
    { especialidade: "Audiometria", servico: "HD São Mateus", meta: "300" },
    { especialidade: "Colpo", servico: "HD São Mateus", meta: "110" },
    { especialidade: "Colono/retossigmoidosc.", servico: "HD São Mateus", meta: "100 e 16 (70 a 80 anos)" },
    { especialidade: "Densitometria", servico: "HD São Mateus", meta: "300" },
    { especialidade: "Endoscopia", servico: "HD São Mateus", meta: "220" },
    { especialidade: "Eletroencefalo sem sed.", servico: "HD São Mateus", meta: "20" },
    { especialidade: "Ecocardiograma", servico: "HD São Mateus", meta: "240" },
    { especialidade: "Holter", servico: "HD São Mateus", meta: "210" },
    { especialidade: "Mamografia", servico: "HD São Mateus", meta: "600" },
    { especialidade: "MAPA", servico: "HD São Mateus", meta: "210" },
    { especialidade: "Teste Ergométrico", servico: "HD São Mateus", meta: "170" },
    { especialidade: "Ultrassom", servico: "HD São Mateus", meta: "840" },
    { especialidade: "Usg Morfológico", servico: "HD São Mateus", meta: "130" },
    { especialidade: "USG Doppler Vascular", servico: "HD São Mateus", meta: "400" },
    { especialidade: "Usg Obstétrica", servico: "HD São Mateus", meta: "550" },
    { especialidade: "USG Transvaginal", servico: "HD São Mateus", meta: "140" },

    // AE São Carlos
    { especialidade: "Cardiologista -Telemedicina", servico: "AE São Carlos", meta: "1/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "AE São Carlos", meta: "1/12h" },
    { especialidade: "Dermatologista", servico: "AE São Carlos", meta: "5/12h (528)" },
    { especialidade: "Dermatologista Procedimento", servico: "AE São Carlos", meta: "2/12h" },
    { especialidade: "Dermatologista Hanseniase", servico: "AE São Carlos", meta: "1/4h" },
    { especialidade: "Endocrinologista", servico: "AE São Carlos", meta: "2/12h" },
    { especialidade: "GO PNAR", servico: "AE São Carlos", meta: "2/12h" },
    { especialidade: "GO Colpo", servico: "AE São Carlos", meta: "1/12h" },
    { especialidade: "Neurologia", servico: "AE São Carlos", meta: "1/12h" },
    { especialidade: "Otorrinolaringologista", servico: "AE São Carlos", meta: "2/12h" },
    { especialidade: "Oftalmologista", servico: "AE São Carlos", meta: "1/12h" },
    { especialidade: "Pneumo Adulto", servico: "AE São Carlos", meta: "3/12h" },
    { especialidade: "Urologista", servico: "AE São Carlos", meta: "1/12h" },
    { especialidade: "Audiometria", servico: "AE São Carlos", meta: "600" },
    { especialidade: "Ecocardiograma", servico: "AE São Carlos", meta: "100" },
    { especialidade: "Espirometria", servico: "AE São Carlos", meta: "400" },
    { especialidade: "Holter", servico: "AE São Carlos", meta: "200" },
    { especialidade: "Mamografia", servico: "AE São Carlos", meta: "600" },
    { especialidade: "MAPA", servico: "AE São Carlos", meta: "100" },
    { especialidade: "Nasofibroscopia", servico: "AE São Carlos", meta: "60" },
    { especialidade: "Teste Ergométrico", servico: "AE São Carlos", meta: "40" },
    { especialidade: "Ultrassom", servico: "AE São Carlos", meta: "350" },
    { especialidade: "Ultrassom Doppler", servico: "AE São Carlos", meta: "250" },

    // AE Burgo
    { especialidade: "Angiologista", servico: "AE Burgo", meta: "1/12h" },
    { especialidade: "Dermatologista", servico: "AE Burgo", meta: "3/12h" },
    { especialidade: "Dermatologista Procedimento", servico: "AE Burgo", meta: "1/6h" },
    { especialidade: "Dermatologista Telemedicina", servico: "AE Burgo", meta: "1/20h" },
    { especialidade: "Endocrinologista", servico: "AE Burgo", meta: "4/12h" },
    { especialidade: "Gastroenterologista", servico: "AE Burgo", meta: "1/12h" },
    { especialidade: "GO PNAR", servico: "AE Burgo", meta: "1/6h e 2/12h" },
    { especialidade: "Infecto", servico: "AE Burgo", meta: "1/12h - 132" },
    { especialidade: "Neurologista Telemedicina", servico: "AE Burgo", meta: "1/35h" },
    { especialidade: "Otorrinolaringologista", servico: "AE Burgo", meta: "3/12h e 1/6h" },
    { especialidade: "Pneumo Adulto", servico: "AE Burgo", meta: "1/12h" },
    { especialidade: "Urologista", servico: "AE Burgo", meta: "3/12h" },
    { especialidade: "Eletroencefalo sem sed.", servico: "AE Burgo", meta: "50" },
    { especialidade: "Ecocardiograma", servico: "AE Burgo", meta: "200" },
    { especialidade: "Holter", servico: "AE Burgo", meta: "100" },
    { especialidade: "Mamografia", servico: "AE Burgo", meta: "400" },
    { especialidade: "MAPA", servico: "AE Burgo", meta: "80" },
    { especialidade: "Teste Ergométrico", servico: "AE Burgo", meta: "125" },
    { especialidade: "Ultrassom", servico: "AE Burgo", meta: "1761" },
    { especialidade: "Ultrassom Doppler", servico: "AE Burgo", meta: "30" },
    { especialidade: "Usg Morfológico", servico: "AE Burgo", meta: "70" },
    { especialidade: "USG Doppler Vascular", servico: "AE Burgo", meta: "360" },

    // AMA-E Itaquera
    { especialidade: "Angiologista", servico: "AMA-E Itaquera", meta: "3/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "AMA-E Itaquera", meta: "3/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "AMA-E Itaquera", meta: "1/12h" },
    { especialidade: "Dermatologista", servico: "AMA-E Itaquera", meta: "3/12h (364) e 1/6h" },
    { especialidade: "Dermatologista Procedimento", servico: "AMA-E Itaquera", meta: "1/6h" },
    { especialidade: "Dermatologista Hanseniase", servico: "AMA-E Itaquera", meta: "1/4h" },
    { especialidade: "Endocrinologista", servico: "AMA-E Itaquera", meta: "4/12h" },
    { especialidade: "Gastroenterologista", servico: "AMA-E Itaquera", meta: "1/12h" },
    { especialidade: "Hemato", servico: "AMA-E Itaquera", meta: "1/12h" },
    { especialidade: "Infecto", servico: "AMA-E Itaquera", meta: "1/12h" },
    { especialidade: "Neurologia", servico: "AMA-E Itaquera", meta: "5/12h" },
    { especialidade: "Neurologista Pediatrico", servico: "AMA-E Itaquera", meta: "3/12h" },
    { especialidade: "Ortopedia Clinica", servico: "AMA-E Itaquera", meta: "5/12h e 1/6h" },
    { especialidade: "Otorrinolaringologista", servico: "AMA-E Itaquera", meta: "4/12h" },
    { especialidade: "Pneumo Infantil", servico: "AMA-E Itaquera", meta: "1/12h" },
    { especialidade: "Pneumo Adulto", servico: "AMA-E Itaquera", meta: "1/12h" },
    { especialidade: "Reumato", servico: "AMA-E Itaquera", meta: "1/12h" },
    { especialidade: "Audiometria", servico: "AMA-E Itaquera", meta: "415" },
    { especialidade: "Eletroencefalo sem sed.", servico: "AMA-E Itaquera", meta: "66" },
    { especialidade: "Ecocardiograma", servico: "AMA-E Itaquera", meta: "150" },
    { especialidade: "Eletroneuromiografia", servico: "AMA-E Itaquera", meta: "300" },
    { especialidade: "Holter", servico: "AMA-E Itaquera", meta: "300" },
    { especialidade: "MAPA", servico: "AMA-E Itaquera", meta: "200" },
    { especialidade: "Nasofibroscopia", servico: "AMA-E Itaquera", meta: "200" },
    { especialidade: "Otoneurológico", servico: "AMA-E Itaquera", meta: "30" },
    { especialidade: "Teste Ergométrico", servico: "AMA-E Itaquera", meta: "100" },
    { especialidade: "Ultrassom", servico: "AMA-E Itaquera", meta: "550" },
    { especialidade: "USG Doppler Vascular", servico: "AMA-E Itaquera", meta: "150" },

    // UBS Nascer do SOL
    { especialidade: "Dermatologista", servico: "UBS Nascer do SOL", meta: "1/12h (100)" },
    { especialidade: "Dermatologista Hanseniase", servico: "UBS Nascer do SOL", meta: "1/4h" },
    { especialidade: "GO PNAR", servico: "UBS Nascer do SOL", meta: "2/12h" },
    { especialidade: "GO Colpo", servico: "UBS Nascer do SOL", meta: "1/12h" },
    { especialidade: "Ultrassom", servico: "UBS Nascer do SOL", meta: "1200" },

    // CCI
    { especialidade: "Acupunturista", servico: "CCI", meta: "1/40h" },
    { especialidade: "Angiologista", servico: "CCI", meta: "1/12h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "CCI", meta: "3/12h" },
    { especialidade: "Fisiatra", servico: "CCI", meta: "1/20h" },
    { especialidade: "Ortopedia Clinica", servico: "CCI", meta: "11/12h" },
    { especialidade: "Pediatra", servico: "CCI", meta: "5/12h" },
    { especialidade: "Ultrassom", servico: "CCI", meta: "700" },
    { especialidade: "Ultrassom Doppler", servico: "CCI", meta: "300" },

    // CEM
    { especialidade: "Mastologista", servico: "CEM", meta: "1/12h" },
    { especialidade: "Biopsias", servico: "CEM", meta: "LD" },
    { especialidade: "Colpo", servico: "CEM", meta: "130" },
    { especialidade: "Densitometria", servico: "CEM", meta: "150" },
    { especialidade: "Estudo Urododinâmico", servico: "CEM", meta: "200" },
    { especialidade: "Histeroscopia Diag", servico: "CEM", meta: "40" },
    { especialidade: "Mamografia", servico: "CEM", meta: "880" },
    { especialidade: "Ultrassom", servico: "CEM", meta: "2520" },
    { especialidade: "Ultrassom Doppler", servico: "CEM", meta: "480" },

    // AE Boni IV
    { especialidade: "Alergista", servico: "AE Boni IV", meta: "1/20h" },
    { especialidade: "Acupunturista", servico: "AE Boni IV", meta: "2/20h" },
    { especialidade: "Angiologista Direta", servico: "AE Boni IV", meta: "1/20h" },
    { especialidade: "Cardiologista -Telemedicina", servico: "AE Boni IV", meta: "1/20h" },
    { especialidade: "Dermatologista Direta", servico: "AE Boni IV", meta: "1/20h" },
    { especialidade: "GO PNAR", servico: "AE Boni IV", meta: "2/20h" },
    { especialidade: "GO Colpo", servico: "AE Boni IV", meta: "1/20h" },
    { especialidade: "Ortopedia Clinica", servico: "AE Boni IV", meta: "2/20h" },
    { especialidade: "Otorrinolaringologista", servico: "AE Boni IV", meta: "1/20h" },
    { especialidade: "Urologista", servico: "AE Boni IV", meta: "4/20h" },
    { especialidade: "C. Pediatrico", servico: "AE Boni IV", meta: "1/20h" },
    { especialidade: "Teste Ergométrico", servico: "AE Boni IV", meta: "1312" },
    { especialidade: "Ultrassom", servico: "AE Boni IV", meta: "384" },
    { especialidade: "USG Doppler Vascular", servico: "AE Boni IV", meta: "32" }
];